// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QLSV.Models;

public partial class DangKyHocPhan
{
    public string MaHp { get; set; }

    public string MaSv { get; set; }

    public DateOnly? NgayDangKy { get; set; }

    public string TrangThai { get; set; }

    public decimal? DiemChuyenCan { get; set; }

    public decimal? DiemGiuaKy { get; set; }

    public decimal? DiemCuoiKy { get; set; }

    public decimal? DiemTongKet { get; set; }

    public string XepLoai { get; set; }

    public virtual HocPhan MaHpNavigation { get; set; }

    public virtual SinhVien MaSvNavigation { get; set; }
}