// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QLSV.Models;

public partial class GiangVien
{
    public string MaGv { get; set; }

    public string MaKhoa { get; set; }

    public string TenGiangVien { get; set; }

    public string Sdt { get; set; }

    public string Email { get; set; }

    public string GioiTinh { get; set; }

    public DateOnly? NgayVaoTruong { get; set; }

    // true = đang hoạt động, false = đã nghỉ (soft delete)
    public bool? TrangThai { get; set; }

    public virtual ICollection<HocPhan> HocPhans { get; set; } = new List<HocPhan>();

    public virtual ICollection<LopHoc> LopHocs { get; set; } = new List<LopHoc>();

    public virtual Khoa MaKhoaNavigation { get; set; }
}