// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QLSV.Models;

public partial class HocPhan
{
    public string MaHp { get; set; }

    public string MaMh { get; set; }

    public string MaGv { get; set; }

    public int? HocKy { get; set; }

    public string NamHoc { get; set; }

    public int? SiSoToiDa { get; set; }

    public string PhongHoc { get; set; }

    public string LichHoc { get; set; }

    public virtual ICollection<DangKyHocPhan> DangKyHocPhans { get; set; } = new List<DangKyHocPhan>();

    public virtual GiangVien MaGvNavigation { get; set; }

    public virtual MonHoc MaMhNavigation { get; set; }
}