// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QLSV.Models;

public partial class Khoa
{
    public string MaKhoa { get; set; }

    public string MaTruongKhoa { get; set; }

    public string TenKhoa { get; set; }

    public virtual ICollection<GiangVien> GiangViens { get; set; } = new List<GiangVien>();

    public virtual ICollection<LopHoc> LopHocs { get; set; } = new List<LopHoc>();

    public virtual ICollection<MonHoc> MonHocs { get; set; } = new List<MonHoc>();
}