// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QLSV.Models;

public partial class LopHoc
{
    public string MaLop { get; set; }

    public string MaKhoa { get; set; }

    public string MaGv { get; set; }

    public string TenLop { get; set; }

    public string KhoaHoc { get; set; }

    public virtual GiangVien MaGvNavigation { get; set; }

    public virtual Khoa MaKhoaNavigation { get; set; }

    public virtual ICollection<SinhVien> SinhViens { get; set; } = new List<SinhVien>();
}