// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QLSV.Models;

public partial class MonHoc
{
    public string MaMh { get; set; }

    public string MaKhoa { get; set; }

    public string TenMh { get; set; }

    public int SoTinChi { get; set; }

    public virtual ICollection<HocPhan> HocPhans { get; set; } = new List<HocPhan>();

    public virtual Khoa MaKhoaNavigation { get; set; }
}