// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QLSV.Models;

public partial class QLSVContext : DbContext
{
    public QLSVContext(DbContextOptions<QLSVContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DangKyHocPhan> DangKyHocPhans { get; set; }

    public virtual DbSet<GiangVien> GiangViens { get; set; }

    public virtual DbSet<HocPhan> HocPhans { get; set; }

    public virtual DbSet<Khoa> Khoas { get; set; }

    public virtual DbSet<LopHoc> LopHocs { get; set; }

    public virtual DbSet<MonHoc> MonHocs { get; set; }

    public virtual DbSet<SinhVien> SinhViens { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DangKyHocPhan>(entity =>
        {
            entity.HasKey(e => new { e.MaHp, e.MaSv }).HasName("PK__DangKyHo__9557F66D291ABA0E");

            entity.ToTable("DangKyHocPhan");

            entity.Property(e => e.MaHp)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("MaHP");
            entity.Property(e => e.MaSv)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("MaSV");
            entity.Property(e => e.DiemChuyenCan).HasColumnType("decimal(4, 2)");
            entity.Property(e => e.DiemCuoiKy).HasColumnType("decimal(4, 2)");
            entity.Property(e => e.DiemGiuaKy).HasColumnType("decimal(4, 2)");
            entity.Property(e => e.DiemTongKet).HasColumnType("decimal(4, 2)");
            entity.Property(e => e.TrangThai).HasMaxLength(30);
            entity.Property(e => e.XepLoai).HasMaxLength(20);

            entity.HasOne(d => d.MaHpNavigation).WithMany(p => p.DangKyHocPhans)
                .HasForeignKey(d => d.MaHp)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DangKyHocPhan_HocPhan");

            entity.HasOne(d => d.MaSvNavigation).WithMany(p => p.DangKyHocPhans)
                .HasForeignKey(d => d.MaSv)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DangKyHocPhan_SinhVien");
        });

        modelBuilder.Entity<GiangVien>(entity =>
        {
            entity.HasKey(e => e.MaGv).HasName("PK__GiangVie__2725AEF3EFA6E616");

            entity.ToTable("GiangVien");

            entity.HasIndex(e => e.Email, "UQ_GiangVien_Email").IsUnique();

            entity.Property(e => e.MaGv)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("MaGV");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.GioiTinh).HasMaxLength(10);
            entity.Property(e => e.MaKhoa)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Sdt)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("SDT");
            entity.Property(e => e.TenGiangVien)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.MaKhoaNavigation).WithMany(p => p.GiangViens)
                .HasForeignKey(d => d.MaKhoa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GiangVien_Khoa");
        });

        modelBuilder.Entity<HocPhan>(entity =>
        {
            entity.HasKey(e => e.MaHp).HasName("PK__HocPhan__2725A6EC34D6095B");

            entity.ToTable("HocPhan");

            entity.Property(e => e.MaHp)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("MaHP");
            entity.Property(e => e.LichHoc).HasMaxLength(100);
            entity.Property(e => e.MaGv)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("MaGV");
            entity.Property(e => e.MaMh)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("MaMH");
            entity.Property(e => e.NamHoc)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PhongHoc).HasMaxLength(50);

            entity.HasOne(d => d.MaGvNavigation).WithMany(p => p.HocPhans)
                .HasForeignKey(d => d.MaGv)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HocPhan_GiangVien");

            entity.HasOne(d => d.MaMhNavigation).WithMany(p => p.HocPhans)
                .HasForeignKey(d => d.MaMh)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HocPhan_MonHoc");
        });

        modelBuilder.Entity<Khoa>(entity =>
        {
            entity.HasKey(e => e.MaKhoa).HasName("PK__Khoa__6539040511FCFC63");

            entity.ToTable("Khoa");

            entity.Property(e => e.MaKhoa)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.MaTruongKhoa)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.TenKhoa)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<LopHoc>(entity =>
        {
            entity.HasKey(e => e.MaLop).HasName("PK__LopHoc__3B98D273C890299E");

            entity.ToTable("LopHoc");

            entity.Property(e => e.MaLop)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.KhoaHoc)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.MaGv)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("MaGV");
            entity.Property(e => e.MaKhoa)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.TenLop)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.MaGvNavigation).WithMany(p => p.LopHocs)
                .HasForeignKey(d => d.MaGv)
                .HasConstraintName("FK_LopHoc_GiangVien");

            entity.HasOne(d => d.MaKhoaNavigation).WithMany(p => p.LopHocs)
                .HasForeignKey(d => d.MaKhoa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LopHoc_Khoa");
        });

        modelBuilder.Entity<MonHoc>(entity =>
        {
            entity.HasKey(e => e.MaMh).HasName("PK__MonHoc__2725DFD9084483F7");

            entity.ToTable("MonHoc");

            entity.Property(e => e.MaMh)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("MaMH");
            entity.Property(e => e.MaKhoa)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.TenMh)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("TenMH");

            entity.HasOne(d => d.MaKhoaNavigation).WithMany(p => p.MonHocs)
                .HasForeignKey(d => d.MaKhoa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MonHoc_Khoa");
        });

        modelBuilder.Entity<SinhVien>(entity =>
        {
            entity.HasKey(e => e.MaSv).HasName("PK__SinhVien__2725081A2A75B095");

            entity.ToTable("SinhVien");

            entity.HasIndex(e => e.Email, "UQ_SinhVien_Email").IsUnique();

            entity.Property(e => e.MaSv)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("MaSV");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.GioiTinh).HasMaxLength(10);
            entity.Property(e => e.HoTen)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaLop)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.QueQuan).HasMaxLength(100);
            entity.Property(e => e.Sdt)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("SDT");
            entity.Property(e => e.TrangThai).HasMaxLength(30);

            entity.HasOne(d => d.MaLopNavigation).WithMany(p => p.SinhViens)
                .HasForeignKey(d => d.MaLop)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SinhVien_LopHoc");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}