// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QLSV.Models;

public partial class SinhVien
{
    public string MaSv { get; set; }

    public string MaLop { get; set; }

    public string HoTen { get; set; }

    public DateOnly? NgayThangNamSinh { get; set; }

    public string QueQuan { get; set; }

    public string GioiTinh { get; set; }

    public string Sdt { get; set; }

    public string Email { get; set; }

    public DateOnly? NgayNhapHoc { get; set; }

    public string TrangThai { get; set; }

    public virtual ICollection<DangKyHocPhan> DangKyHocPhans { get; set; } = new List<DangKyHocPhan>();

    public virtual LopHoc MaLopNavigation { get; set; }
}